available_locales: ["en", "de"]
default_locale: "de"

currency: "EUR"
currency_symbol: "€"
project_goal: 10000
price: 19.90
# expiration_date: <%= DateTime.now + 29.days %>

num_key_points: 4
num_other_points: 4
num_faqs: 8

payment_mode: 'test'
payment_provider_stripe: true
